src/MD/Bundle/UserBundle/Entity/Person.php
<?php

namespace MD\Bundle\UserBundle\Entity;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use MD\Bundle\MediaBundle\Entity\Image as Image;

/**
 * Person
 *
 * @ORM\Table("person")
 * @ORM\Entity
 */
class Person {

    // Child Type 

    const CHILD = 1;
    // User Type
    const REGULAR = 1;
    const MAIN = 2;
    // metonymy types 
    const TEACHER = 1;
    const DOCTOR = 2;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="\MD\Bundle\CMSBundle\Entity\Seo", inversedBy="person",cascade={"persist"})
     */
    protected $seo;

    /**
     * @Assert\NotBlank()

     * @ORM\Column(name="first_name", type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", nullable=true ,  length=255)
     */
    private $familyname;

    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email.",
     * )
     * @ORM\Column(name="email", type="string", length=225)
     */
    private $email;

    /**
     * @ORM\Column(name="address", nullable=true , type="string", length=255)
     */
    private $address;

    /**
     *
     * @ORM\Column(name="child", type="boolean")
     */
    private $child = false;

    /**
     * @var string
     * @ORM\Column(name="phone", type="string", length=25 ,nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(name="birthdate",nullable=true , type="date" )
     */
    private $birthdate;

    /**
     *
     * @ORM\Column(name="gender", type="boolean", nullable = true)
     */
    private $gender;

    /**
     * @ORM\OneToMany(targetEntity="\MD\Bundle\CMSBundle\Entity\Recipe", mappedBy="person")
     */
    protected $recipes;

    /**
     * @ORM\OneToMany(targetEntity="\MD\Bundle\CMSBundle\Entity\Article", mappedBy="person")
     */
    protected $articles;

    /**
     * @ORM\OneToMany(targetEntity="\MD\Bundle\CMSBundle\Entity\SurveyAnswer", mappedBy="person")
     */
    protected $surveyAnswers;

    /**
     * @ORM\OneToMany(targetEntity="\MD\Bundle\CMSBundle\Entity\Tip", mappedBy="person")
     */
    protected $tips;

    /**
     * @ORM\OneToOne(targetEntity="\MD\Bundle\CMSBundle\Entity\ArticleFavorite", mappedBy="person")
     */
    protected $articleFavorite;

    /**
     * @ORM\OneToOne(targetEntity="\MD\Bundle\CMSBundle\Entity\FadfadaFavorite", mappedBy="person")
     */
    protected $fadfadaFavorite;

    /**
     * @ORM\OneToOne(targetEntity="\MD\Bundle\CMSBundle\Entity\RecipeFavorite", mappedBy="person")
     */
    protected $recipeFavorite;

    /**
     * @ORM\OneToMany(targetEntity="Account", mappedBy="person")
     */
    protected $accounts;

    /**
     * @ORM\ManyToMany(targetEntity="\MD\Bundle\MediaBundle\Entity\Image")
     */
    protected $images;

    /**
     * @ORM\OneToMany(targetEntity="Follower", mappedBy="follower")
     */
    protected $followers;

    /**
     * @ORM\OneToMany(targetEntity="Follower", mappedBy="person")
     */
    protected $followerPersons;

    /**
     * @ORM\OneToMany(targetEntity="MenuPlanner", mappedBy="person")
     */
    protected $menuPlanners;

    /**
     * @ORM\OneToMany(targetEntity="SuperMarket", mappedBy="person")
     */
    protected $superMarkets;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    public function getEmail() {
        return $this->email;
    }

    public function setEmail($email) {
        $this->email = $email;
    }

    /**
     * Set birthdate
     *
     * @param \DateTime $birthdate
     * @return Person
     */
    public function setBirthdate($birthdate) {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * Get birthdate
     *
     * @return \DateTime 
     */
    public function getBirthdate() {
        return $this->birthdate;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return Person
     */
    public function setPhone($phone) {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone() {
        return $this->phone;
    }

    /**
     * Set gender
     *
     * @param boolean $gender
     * @return Person
     */
    public function setGender($gender) {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return boolean 
     */
    public function getGender() {
        return $this->gender;
    }

    /**
     * Add accounts
     *
     * @param \MD\Bundle\UserBundle\Entity\Account $accounts
     * @return Person
     */
    public function addAccount(\MD\Bundle\UserBundle\Entity\Account $accounts) {
        $this->accounts[] = $accounts;

        return $this;
    }

    /**
     * Remove accounts
     *
     * @param \MD\Bundle\UserBundle\Entity\Account $accounts
     */
    public function removeAccount(\MD\Bundle\UserBundle\Entity\Account $accounts) {
        $this->accounts->removeElement($accounts);
    }

    /**
     * Get accounts
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAccounts() {
        return $this->accounts;
    }

    /**
     * Get accounts
     *
     * @return \MD\Bundle\UserBundle\Entity\Account 
     */
    public function getFirstAccount() {
        if (count($this->accounts) > 0) {
            return $this->accounts[0];
        } else {
            return NULL;
        }
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setFirstName($firstName) {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName() {
        return $this->firstName;
    }

    /**
     * Set address
     *
     * @param string $address
     * @return Person
     */
    public function setAddress($address) {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string 
     */
    public function getAddress() {
        return $this->address;
    }

    /**
     * Set child
     *
     * @param boolean $child
     * @return Person
     */
    public function setChild($child) {
        $this->child = $child;

        return $this;
    }

    /**
     * Get child
     *
     * @return boolean 
     */
    public function getChild() {
        return $this->child;
    }

    public function __toString() {
        return $this->getFirstName();
    }

    /**
     * Add images
     *
     * @param \MD\Bundle\MediaBundle\Entity\Image $images
     * @return Person
     */
    public function addImage(\MD\Bundle\MediaBundle\Entity\Image $images) {
        $this->images[] = $images;

        return $this;
    }

    /**
     * Remove images
     *
     * @param \MD\Bundle\MediaBundle\Entity\Image $images
     */
    public function removeImage(\MD\Bundle\MediaBundle\Entity\Image $images) {
        $this->images->removeElement($images);
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getImages($types = FALSE) {
        if ($types) {
            return $this->images->filter(function($image) use ($types) {
                        return in_array($image->getImageType(), $types);
                    });
        } else {
            return $this->images;
        }
    }

    /**
     * Get logoImage
     *
     * @return MD\Bundle\MediaBundle\Entity\Image
     */
    public function getLogoImage() {
        return $this->getImages(array(Image::TYPE_LOGO))->first();
    }

    /**
     * Get passportImage
     *
     * @return MD\Bundle\MediaBundle\Entity\Image
     */
    public function getImage() {
        return $this->getImages(array(Image::TYPE_GALLERY))->first();
    }

    /**
     * Set image
     *
     * @param \MD\Bundle\MediaBundle\Entity\Image $image
     * @return Banner
     */
    public function setImage(\MD\Bundle\MediaBundle\Entity\Image $image = null) {
        $this->images[0] = $image;
        return $this;
    }

    /**
     * Set familyname
     *
     * @param string $familyname
     * @return Person
     */
    public function setFamilyname($familyname) {
        $this->familyname = $familyname;

        return $this;
    }

    /**
     * Get familyname
     *
     * @return string 
     */
    public function getFamilyname() {
        return $this->familyname;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->recipes = new \Doctrine\Common\Collections\ArrayCollection();
        $this->articles = new \Doctrine\Common\Collections\ArrayCollection();
        $this->surveyAnswers = new \Doctrine\Common\Collections\ArrayCollection();
        $this->tips = new \Doctrine\Common\Collections\ArrayCollection();
        $this->accounts = new \Doctrine\Common\Collections\ArrayCollection();
        $this->images = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add recipes
     *
     * @param \MD\Bundle\CMSBundle\Entity\Recipe $recipes
     * @return Person
     */
    public function addRecipe(\MD\Bundle\CMSBundle\Entity\Recipe $recipes) {
        $this->recipes[] = $recipes;

        return $this;
    }

    /**
     * Remove recipes
     *
     * @param \MD\Bundle\CMSBundle\Entity\Recipe $recipes
     */
    public function removeRecipe(\MD\Bundle\CMSBundle\Entity\Recipe $recipes) {
        $this->recipes->removeElement($recipes);
    }

    /**
     * Get recipes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */

src/MD/Bundle/UserBundle/Resources/views/FrontEnd/Usr/AdminVerifyEmail.html.twig
<!DOCTYPE html>
<html>
    <head>
        <title>ABLA TAZZA | e-mail</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body style="background: #efefef;direction: rtl; text-align:right;font-family:Helvetica;padding: 15px 0;">
        <div style="width: 640px;margin: 30px auto">
            <div style="clear: both;text-align: center;">
                <img src="{{ app.request.scheme ~ "://" ~ app.request.host }}{{ asset('bundles/fe/images/logo.png') }}" alt="أبلة طازة"/>
                <div style="background-color: #dff0d8;border:1px solid #d6e9c6;color: #3c763d;padding: 10px 0; font-weight: bold;width: 90%;margin: 0 auto;">تم التسجيل بنجاح</div>
            </div>
            <div style="border: 1px solid #cdcbcc;overflow: hidden;background: #fff;width: 90%;margin: 0 auto;">
                <div style="width: 90%;margin-top: 10px;padding: 0 5%;clear: both;overflow: hidden">
                    <div style="width: 100%;clear: both;margin:40px auto 25px;">
                        <div style="width: 100%;">
                            <p style="text-decoration:none;background: #e82327;color:#fff;text-align: center;cursor: pointer;font-size: 14px;padding: 6px 12px;font-weight: 400;border-radius: 4px;-webkit-border-radius: 4px;-o-border-radius: 4px;-ms-border-radius: 4px;-moz-border-radius: 4px;">
                                تم تنشيط حسابك
                            </p>
                            <p style="text-align:left;direction:ltr;"> This is an automated email message; please do not reply. Replies to this message are routed to an unmonitored mailbox.  </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

src/MD/Bundle/UserBundle/Resources/views/FrontEnd/Usr/VerifyEmail.html.twig
<!DOCTYPE html>
<html>
    <head>
        <title>ABLA TAZZA | e-mail</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body style="background: #efefef;direction: rtl; text-align:right;font-family:Helvetica;padding: 15px 0;">
        <div style="width: 640px;margin: 30px auto">
            <div style="clear: both;text-align: center;">
                <img src="{{ app.request.scheme ~ "://" ~ app.request.host }}{{ asset('bundles/fe/images/logo.png') }}" alt="أبلة طازة"/>
                <div style="background-color: #dff0d8;border:1px solid #d6e9c6;color: #3c763d;padding: 10px 0; font-weight: bold;width: 90%;margin: 0 auto;">تم التسجيل بنجاح</div>
            </div>
            <div style="border: 1px solid #cdcbcc;overflow: hidden;background: #fff;width: 90%;margin: 0 auto;">
                <div style="width: 90%;margin-top: 10px;padding: 0 5%;clear: both;overflow: hidden">
                    <div style="width: 100%;clear: both;margin:40px auto 25px;">
                        <div style="width: 100%;text-align: center;">
                            <a href="{{ app.request.scheme ~ "://" ~ app.request.host }}{{path("fe_email_verify" , { "code" : verifyCode })}}" style="text-decoration:none;background: #e82327;color:#fff;text-align: center;cursor: pointer;font-size: 14px;padding: 6px 12px;font-weight: 400;border-radius: 4px;-webkit-border-radius: 4px;-o-border-radius: 4px;-ms-border-radius: 4px;-moz-border-radius: 4px;">
                                قم بتنشيط حسابك بالضغط هنا
                            </a>
                            <p style="text-align:right;direction:rtl;"> هذه رسالة البريد الإلكتروني الآلي. يرجى عدم الرد. يتم توجيه الردود على هذه الرسالة إلى علبة بريد غير خاضعة للرقابة. </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

src/MD/Bundle/UserBundle/Resources/views/FrontEnd/Usr/cancelEmail.html.twig
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Tour Voucher</title>
        </head>
        <body bgcolor="#ffffff" style="direction:rtl; " >
            <table cellpadding="0" cellspacing="0" style="margin-top:35px;" width="620" align="center" border="0">
                <tr>
                    <td style="direction: ltr;padding-bottom:10px;">
                        <span style="text-align:left; font-family:arial; color:#7d7d7d; font-size:12px; line-height:16px;">This is an automated email message; please do not reply. Replies to this message are routed to an unmonitored mailbox. If you have questions please contact us on support@theholidayers.com or call us on: +2010 76876787</span>
                    </td>
                </tr>
                <tr>
                    <td style="background:url('http://88.80.188.68:8084/bundles/fe/images/email-banner.png'); width:100%; height:50px;"></td>
                </tr>
                <td style="position: relative;">
                    <p style="float:right;color:ed2024; font-size:25px; font-family:'cocon';">حجز رقم
                        <span class="numbers_font">{{booking.id}}</span>
                    </p>
                    <img style="left: 0;position: absolute;top: -20px;" src="http://88.80.188.68:8084/bundles/fe/images/email-logo.png">
                </td>
                <tr>
                    <td>
                        <table style=' width: 100%; height: 202px; background:#f2dede; border-radius: 4px; /* -moz-border-radius: 4px; -webkit-border-radius: 4px; */ '>
                            <tr>
                                <td style="width:148px; height:105px;padding-right: 28px; ">
                                    <img src="http://88.80.188.68:8084/bundles/fe/images/email-72.png">
                                </td>
                                <td style="padding-right:27px;  padding-left:23px; font-family: 'cocon';">
                                    <table>
                                        <tr>
                                            <td style="padding-top:30px; display:block; color:#ed1f24; font-size:24px;">تم إلغاء الحجز تلقائياً.</td>
                                        </tr>
                                        <tr>
                                            <td style="font-size:18px;">كان نفسنا تسافر وتلف الدنيا معانا!</td>
                                        </tr>
                                        <tr>
                                            <td style="font-family:'cocon-light';font-size:16px; width:400px; line-height:28px;">علي العموم لسه في فرصة تانية أنك تكمل أو تعدل حجزك وتلحق رحلتك. قم بتفعيل الحجز مرة أخري وسوف يتواصل معك أحد مسئولي خدمة العملاء للرد علي كل إستفساراتك ومتابعة تفاصيل الحجز.</td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="height:27px; width:100%;"></td>
                </tr>
                                {%set days = booking.packageTrip.package.nigthsCount +1 %}

                <tr style="">
                    <td style="border-top:1px solid #cecfd7;border-bottom:1px solid #cecfd7;">
                        <table cellspacing="0" cellpadding="0" style=''>
                            <tr style="font-family: 'cocon';">
                                <td style="height:187px;">
                                    <img style="float: right; padding-top: 9px;"  {%if booking.packageTrip.package.mainImage%}src="http://88.80.188.68:8084{{ asset("uploads/packages/" ~ booking.packageTrip.package.id ~ "/" ~ "th" ~ booking.packageTrip.package.mainImage.id) }}"{%else%}src="http://88.80.188.68:8084/bundles/fe/images/email-trip.png" {%endif%}>
                                    <p style="padding-top:18px; color: #4f3183; font-family: 'cocon';">
                                        <span style="font-family:'cocon-light'; font-size: 14px;">السعر الإجمالي</span>
                                        <br>
                                        <strong class="numbers_font" style="font-size: 30px;">{{booking.getFormatGrandTotal()}}</strong>جنية</p>
                                </td>
                                <td valign="top" style="padding-right:13px;padding-left:70px;">
                                    <h3 style="color: #1c1c1c; font-size: 26px;line-height: 26px; margin-bottom: 5px; margin-top:20px;font-family:'cocon-light';">{{booking.packageTrip.package.name}}</h3>
                                    <small style="display: block;font-size: 12px;line-height: 24px;color: #898989;">
                                        <span style="font-size:14px;font-family:'cocon-light';" class="numbers_font">تاريخ الحجز: {{booking.created|arabic_date_format}}</span>
                                    </small>
                                </td>
                                <td style="color: #4f3183;border-right: 1px solid #cccccc; height: inherit; position: relative;">
                                    <span style="display: block;font-size:13px;font-family:'cocon-light'; margin-right: 11px; background: url(../http://88.80.188.68:8084/bundles/fe/images/plane-right.png) no-repeat right; padding: 0 25px 0 0; margin-top: 21px;">تاريخ السفر</span>
                                    <span style="display: block;font-size:13px;font-family:'cocon-light';margin-right: 11px;">
                                        <strong style="font-size: 24px;" class="numbers_font"></strong>{{booking.arrivalDate|arabic_date_format}}</span>
                                    <hr style="margin-left: 0px;height: 1px;border: none;background: #e5e5e5;margin-top: 20px;">
                                    <span style="display: block;font-size:13px;font-family:'cocon-light'; margin-right: 11px; background: url(../http://88.80.188.68:8084/bundles/fe/images/plane-left.png) no-repeat right; padding: 0 25px 0 0; margin-top: 21px;">تاريخ الرجوع</span>
                                    <span  style="display: block;font-size:13px;font-family:'cocon-light';margin-right: 11px;">
                                        <strong  style="font-size: 24px;" class="numbers_font"  class="numbers_font"></strong>{{booking.arrivalDate|date_modify('+ ' ~days ~ ' days')|arabic_date_format}}</span>

                                </td>
                                <td>
                                    <span  class="numbers_font" style="display:block; background:url('http://88.80.188.68:8084/bundles/fe/images/email-days.png')no-repeat;width:67px; color:#b897f3; height:37px; line-height:37px; margin-top: -10px;position: absolute;margin-right: -37px;">&nbsp;&nbsp;&nbsp;&nbsp;{{days}}</span>   
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="height:40px; width:100%;">

                    </td>
                </tr>
                <tr>
                    <td>
                        <!-- <input style="width: 332px; height: 53px; font-size:20px; margin:0 auto; background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#71c548), to(#4fab32));
     background: -webkit-linear-gradient(top, #71c548, #4fab32);
     background: -moz-linear-gradient(top, #71c548, #4fab32);
     background: -ms-linear-gradient(top, #71c548, #4fab32);
     background: -o-linear-gradient(top, #71c548, #4fab32);
     filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#71c548', endColorstr='#4fab32');
     border: 1px solid #3c8220;
     -moz-border-radius: 4px;
     border-radius: 4px;
     -webkit-border-radius: 4px;
     color: #ffffff;
     font-family: 'cocon';
     text-align: center;
     display: block;
     cursor: pointer;" type="submit" id="" onfocus="" value="تفعيل الحجز لمدة 3 أيام أخري">-->
                    </td>
                </tr>
                <tr><td style="height:9px; background:#e6e7eb; width:100%;"></td></tr>
                <tr>
                    <td>
                        <span style="text-align:center; display:block; color:#363636; line-height:23px; font-size:12px;font-family:'cocon-light';padding-top:22px;">
                            تذكر إنه يمكنك مراجعة حجوزات رحلاتك من خلال حسابك الشخصي في صفحة “رحلاتي”<br>
                            إذا كان لديك أي إستفسارات، من فضلك لاتتردد أن تزور موقعنا والتحدث مع أحد مسئولي خدمة العملاء<br>.
                            مرة أخري، شكراً علي إختيارك لموقع ذاهوليدايرز<br>.
                            إستمتع برحلتك!
                        </span>
                <tr>
                    <td>
                        <img  style="margin:0 auto; padding-top:15px; padding-bottom:15px; display:block;" src="http://88.80.188.68:8084/bundles/fe/images/email-footer-logo.png">        
                    </td>
                </tr>

                <tr>
                    <td>
                        <span style="text-align:center; display:block; color:#363636; line-height:23px; font-size:12px;font-family:'cocon-light';">
                            فريق عمل ذاهوليدرز <br> 
                            من فضلك لاترسل إيميل مباشر رداً علي هذه الرسالة، إتصل بنا  <a href="#" style='color:#363636;'> من هنا</a>.
                        </span>
                    </td>
                </tr>
                <tr>
                    <td style=" padding-top: 5px; padding-bottom: 21px; ">
                        <a href="#" style='margin-right:300px; width:16px; height:16px;'><img src="http://88.80.188.68:8084/bundles/fe/images/facebook2.png"></a>
                        <a href="#" style='width:16px; height:16px;'><img src="http://88.80.188.68:8084/bundles/fe/images/twitter.png"></a>
                    </td>
                </tr>
            </td>
        </tr>
        <tr><td style="height:9px; background:#e6e7eb; width:100%;"></td></tr>
        <tr>
            <td>
                <span style="padding-top:26px;font-size:12px; line-height:20px; color:#b0b0b0; display:block; text-align:center;font-family:'cocon-light';">
                    موقع ذا الهوليديرز www.theholidayers.com  تحت إدارة شركة توريكو للسياحة. حقوق المحتوي والملكية الفكرية والتصميم والصور محفوظة لشركة VIRAL 21 للإستسمارات والتسويق (شركة مساهمة مصرية)
                </span>
            </td>
        </tr>
    </table>
</body>

</html>

src/MD/Bundle/UserBundle/Resources/views/FrontEnd/Usr/viewFollower.html.twig
{% extends 'FEBundle::base.html.twig' %}
{% block title %}المتابعين{% endblock %}

{% block breadcrumb %}
    <div class="home-carousel-one carousel-second-style owl-carousel">
        {{ render(controller('CMSBundle:FrontEnd/Banner:Banner' , {'placment' : 1 })) }}
    </div>
    <div class="page-banner" style="background: #e82327;;">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="page-title pull-right"><i class="fa fa-user"></i> متابعين {{ person.firstName ~ ' ' ~ person.familyName }}</h2>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li><a href="{{ path('fe_home') }}">الرئيسية</a></li>
                        <li><a href="{{ path('fe_show_profile', {'slug':person.seo.slug}) }}">{{ person.firstName ~ ' ' ~ person.familyName }}</a></li>
                        <li>المتابعين</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="user-profile">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <figure class="user-photo thumbnail-hover" style="display: block;margin:-44px auto 0;float: none;">
                        <a href="{{ path('fe_show_profile', {'slug':person.seo.slug}) }}">
                            {% if person.image != null %}
                                <img src="{{ asset('uploads/person/'~person.id~'/'~person.image.id) }}" alt="{{ person.firstName }}"/>
                            {% elseif person.firstAccount.userFacebook != null %}
                                <img src="https://graph.facebook.com/{{ person.firstAccount.userFacebook.facebookId }}/picture?type=large&width=201&height=201"  alt="{{ person.firstName }}"/>
                            {% else %}    
                                <img src="{{ asset('bundles/fe/images/user-2.jpg') }}" alt="{{ person.firstName }}"/>
                            {% endif %}
                        </a>
                    </figure>
                    <div style="overflow: hidden" class="text-center">
                        <div class="col-md-12">
                            <h2 class="user-name" style="padding: 7px 20px;right: 0px;">{{ person.firstName ~ ' ' ~ person.familyName }}</h2>
                            <p>البريد الإلكترونى : {{ person.email }}</p>
                            {% if app.user != null and app.user.person.id != person.id %}
                                {% if app.user.person.isFollower(person.id) == false %}
                                    <a class="btn btn-info btn-block follow" href="javascript:;" style="margin: 0 auto!important;width: 100px">تابعنى</a> 
                                {% else %}
                                    <a href="javascript:;" class="btn btn-warning btn-block follow" style="margin: 0 auto!important;width: 100px">إلغاء المتابعة</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="page-wrapper user-accounts myAccount">
        <div class="container">
            <div class="row">
                <div class="col-md-12 recipe-request-form-column">
                    <h3 class="heading-bottom-line" style="color: #73bc11;">المتابعين</h3>
                    {% if followers|length > 0 %}
                        {% for follower in followers %}
                            <div class="col-xs-2 text-center">
                                <a href="{{ path('fe_show_profile', {'slug':follower.seo.slug}) }}">
                                    {% if follower.image != null %}
                                        <img src="{{ asset('uploads/person/'~follower.id~'/'~follower.image.id) }}" class="img-circle" style="height: 120px" alt="{{ follower.firstName }}"/>
                                    {% elseif follower.firstAccount.userFacebook != null %}
                                        <img src="https://graph.facebook.com/{{ follower.firstAccount.userFacebook.facebookId }}/picture?type=large&width=201&height=201" class="img-circle" style="height: 120px" alt="{{ follower.firstName }}"/>
                                    {% else %}    
                                        <img src="{{ asset('bundles/fe/images/user.jpg') }}" class="img-circle" style="height: 120px" alt="{{ follower.firstName }}"/>
                                    {% endif %}
                                    <h3 style="margin:5px auto;">{{ follower.firstName }}</h3>
                                    {#<h4 style="margin:5px auto;">{{ follower.recipeCount }} وصفة</h4>#}
                                </a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-warning">لا يوجد متابعين حتى الأن</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block javascript %}
    {{ parent() }}
    <script>
        $('.follow').click(function () {
            $this = $(this);
            var data_url = $(this).parent().attr('data-url');
            $this.attr("disabled", 'disabled');
            $.ajax({
                type: "POST",
                url: data_url,
                success: function (result) {
                    if (result == 1) {
                        $this.empty().text('إلغاء المتابعة');
                        $('.follow').removeAttr("disabled");
                        $this.removeClass('btn-info');
                        $this.addClass('btn-warning');
                    }
                    if (result == 0) {
                        $this.empty().text('تابعني');
                        $('.follow').removeAttr("disabled");
                        $this.addClass('btn-info');
                        $this.removeClass('btn-warning');
                    }
                }
            });
        });
    </script>
{% endblock %}